env:
  global:
  - GCP_PROJECT_ID=terraf-travis
  - tf_version=0.13.4
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_953d6d049e2a_key -iv $encrypted_953d6d049e2a_iv -in terraf-travis-0ed3ec96e515.json.enc -out terraf-travis-0ed3ec96e515.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=terraf-travis-0ed3ec96e515.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./terraf-travis-0ed3ec96e515.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
