env:
  global:
  - GCP_PROJECT_ID=terraf-travis
  - tf_version=0.13.4
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_dec7cc46d8e2_key -iv $encrypted_dec7cc46d8e2_iv -in terraf-travis-76081645828d.json.enc -out terraf-travis-76081645828d.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=terraf-travis-76081645828d.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./terraf-travis-76081645828d.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
